### ISSUE TITLE
Can this package support complex matrix inversion?

### ISSUE THREAD

**Issue by xichaoqiang** [Yunhui-Gao/ISTA#1]
Dear Gao,

Can this package support complex matrix inversion?

Best regards,
Xi

**Comment by Yunhui-Gao** [comment]
Hi Xi,

Currently this package only supports real-valued matrices. Nevertheless, I think a common way to deal with complex matrices is to treat each complex-valued variable as two independent real-valued variables (for example, by treating the real part and the imaginary part separately). I'm not sure whether this works in your case. If so, I believe the package can be easily extended to support complex operations.

Best,
Gao
